### ISSUE TITLE
Repo Outdated

### ISSUE THREAD

**Issue by Wh1teHat65** [fluxion/fluxion#1]
Really like this project and have used for a while, but it seems abandoned.  Any hope you might be willing to relook at this and publish an update?

**Comment by fjarri** [comment]
Thanks, I would really like to continue working on it too, but since the last year I've been pretty busy with work, and I could not really decide which direction to move so that I do not directly compete with [DifferentialEquations.jl](https://github.com/JuliaDiffEq/DifferentialEquations.jl) — it's a great package, but I am not happy with its interface in the area I'm interested in (in general, stochastic PDEs, but there are nuances in the problem definition and result processing that DiffEq does not seem to cover by design). 

The main thing that bothered me was repeating code for processing expression trees of arrays and fields, so recently I've started a simple symbolic algebra library to generalize it — no complicated simplification algorithms, just a convenient API to define your own symbol types and relations between them, and traverse the resulting tree. I'm hoping to put something on github in a few weeks, and then use it in Fluxion. I must admit, I am not sure how much time I will be able to dedicate to it, but I am interested in the project myself, so I'll do my best.

By the way, just curious, what did you use it for? It's really just a proof of concept now, far from being practical.

**Comment by Wh1teHat65** [comment]
I was using Fluxion, which is your integrated wifi scanning and penetration testing tool.  My team uses it on the various Pentest engagements we provide to customers.  

I think you may have confused the repo I was referring to.

 

Ken

**Comment by fjarri** [comment]
Oh, I see, the one that you want is [this one](https://github.com/wi-fi-analyzer/fluxion) it seems. Well, if anyone interested in my project is reading this, I stand by my words :)
